// packages/obsidian/src/settings/PropertyMappingModelsComponent.tsx
import { For } from 'solid-js';
import { type PropertyMappingModelData } from './PropertyMapping';
import PropertyMappingModelComponent from './PropertyMappingModelComponent';

interface PropertyMappingModelsComponentProps {
	models?: PropertyMappingModelData[];
	save: (model: PropertyMappingModelData) => void;
}

export default function PropertyMappingModelsComponent(props: PropertyMappingModelsComponentProps) {
	return (
		<div class="setting-item" style={{ display: 'flex', gap: '10px', 'flex-direction': 'column', 'align-items': 'stretch' }}>
			<For each={props.models || []}>{model => <PropertyMappingModelComponent model={model} save={props.save} />}</For>
		</div>
	);
}

// src/settings/PropertyMappingModelsComponent.svelte
<script lang="ts">
	import { PropertyMappingModel } from './PropertyMapping';
	import PropertyMappingModelComponent from './PropertyMappingModelComponent.svelte';

	interface Props {
		models?: PropertyMappingModel[];
		save: (model: PropertyMappingModel) => void;
	}

	let { models = [], save }: Props = $props();
</script>

<div class="setting-item" style="display: flex; gap: 10px; flex-direction: column; align-items: stretch;">
	{#each models as model}
		<PropertyMappingModelComponent {model} {save}></PropertyMappingModelComponent>
	{/each}

	<!--
		<pre>{JSON.stringify(models, null, 4)}</pre>
	-->
</div>

<style>
</style>
